FROM rocker/rstudio:4.0.5

# install additional system dependencies
RUN apt-get update && apt-get install -y libxml2-dev zlib1g-dev libgit2-dev libgdal-dev libproj-dev libgeos-dev libudunits2-dev libv8-dev libprotobuf-dev protobuf-compiler libjq-dev

# set CRAN repo to the RStudio mirror
RUN echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site

# install renv
RUN Rscript -e "install.packages('renv')"

CMD ["/init"]
